spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      boostrap: true
      server:
        native:
          search-locations: classpath:/configs
server:
  port: 8071